elasticsearch:
  build: ./elasticsearch
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "9200:9200"

kibana:
  build: ./kibana
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - elasticsearch
  ports:
    - "5601:5601"

fluentd:
  build: ./fluentd
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - out:/var/out_home
  links:
    - elasticsearch
  ports:
    - "24224:24224"

# slackのログボット
logger:
  build: ./logger
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - fluentd
    - elasticsearch
  env_file:
    - ./logger/slack.env

# slackのfluentd生ログ
rawlog:
  image: ruby:latest
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - out:/out:ro
  expose:
    - "8889"
  ports:
    - "8889:8889"
  command: ruby -run -e httpd -- -p 8889 /out
